# Generated by Django 3.2.4 on 2022-09-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactus',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Mob',
            new_name='Mobile',
        ),
    ]
