# Generated by Django 3.2.4 on 2022-09-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220902_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='ssubject',
        ),
        migrations.AddField(
            model_name='slider',
            name='ssub',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Mobile',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='igallery',
            name='gpic',
            field=models.ImageField(default='', upload_to='static/gallery/'),
        ),
    ]
