# Generated by Django 3.2.4 on 2022-09-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_myblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccity', models.CharField(max_length=30)),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='imembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=20)),
                ('mpincode', models.IntegerField(max_length=25)),
                ('mcity', models.CharField(max_length=50)),
                ('memail', models.CharField(max_length=40)),
                ('mbank', models.IntegerField(max_length=35)),
                ('mcompany', models.CharField(max_length=100)),
                ('maddress', models.CharField(max_length=200)),
            ],
        ),
    ]
