# Generated by Django 3.2.4 on 2022-09-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220907_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='icountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='idonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damount', models.IntegerField()),
                ('dfname', models.CharField(max_length=15)),
                ('dlname', models.CharField(max_length=15)),
                ('demail', models.CharField(max_length=15)),
                ('dphone', models.IntegerField()),
                ('dcountry', models.CharField(max_length=50)),
                ('dadd', models.TextField()),
                ('dstate', models.CharField(max_length=50)),
                ('dcode', models.IntegerField()),
                ('doccu', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='istate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statei', models.CharField(max_length=100)),
            ],
        ),
    ]
