# Generated by Django 3.2.4 on 2022-09-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_icountry_idonate_istate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myblog',
            new_name='iblog',
        ),
    ]
